from groupAnagrams.main import Solution


class TestGroupAnagrams:
    value = 0

    def test_one(self):
        so = Solution()
        self.value = so.groupAnagrams([""])
        assert self.value == [[""]]

    def test_two(self):
        so = Solution()
        self.value = so.groupAnagrams(["eat", "tea", "tan", "ate", "nat", "bat"])
        assert sorted(self.value) == sorted([["bat"], ["nat", "tan"], ["ate", "eat", "tea"]])

    def test_three(self):
        so = Solution()
        self.value = so.groupAnagrams(["a"])
        assert self.value == [["a"]]

    def test_four(self):
        so = Solution()
        self.value = so.groupAnagrams(
            ["nozzle", "punjabi", "waterlogged", "imprison", "crux", "numismatists", "sultans", "rambles",
             "deprecating",
             "aware", "outfield", "marlborough", "guardrooms", "roast", "wattage", "shortcuts", "confidential",
             "reprint",
             "foxtrot", "dispossession", "floodgate", "unfriendliest", "semimonthlies", "dwellers", "walkways",
             "wastrels",
             "dippers", "engrossing", "undertakings", "unforeseen", "oscilloscopes", "pioneers", "geller", "neglects",
             "cultivates", "mantegna", "elicit", "couriered", "shielded", "shrew", "heartening", "lucks", "teammates",
             "jewishness", "documentaries", "subliming", "sultan", "redo", "recopy", "flippancy", "rothko", "conductor",
             "e", "carolingian", "outmanoeuvres", "gewgaw", "saki", "sarah", "snooping", "hakka", "highness", "mewling",
             "spender", "blockhead", "detonated", "cognac", "congaing", "prissy", "loathes", "bluebell", "involuntary",
             "aping", "sadly", "jiving", "buffalo", "chided", "instalment", "boon", "ashikaga", "enigmas",
             "recommenced",
             "snell", "parsley", "buns", "abracadabra", "forewomen", "persecuted", "carsick", "janitorial", "neonate",
             "expeditiously", "porterhouse", "bussed", "charm", "tinseled", "pencils", "inherits", "crew", "estimate",
             "blacktop", "mythologists", "essequibo", "dusky", "fends", "pithily", "positively", "participants", "brew",
             "tows", "pentathlon", "misdiagnoses", "paraphrase", "telephoning", "engining", "anglo", "duisburg",
             "shorthorns", "physical", "enquiries", "grudging", "floodlit", "safflower", "asphalts", "representing",
             "airbrush", "bedevilling", "fulminations", "peacefuller", "hurl", "unequalled", "wiser", "vinson",
             "paglia",
             "doggones", "optimist", "rulering", "katmandu", "flutists", "sterling", "oregonians", "boosts", "slaver",
             "straightedges", "stendhal", "defaulters", "stylize", "chucking", "adulterate", "partaking", "omelettes",
             "monochrome", "bitched", "foxhound", "tapir", "vocalizing", "manifolding", "northerner", "ineptly",
             "dunce",
             "matchbook", "locutions", "docudrama", "sinkers", "paralegal", "sip", "maliced", "lechers", "zippy",
             "tillman",
             "penknives", "olympias", "designates", "mossiest", "leanne", "lavishing", "understate", "underwriting",
             "showered", "belittle", "propounded", "gristly", "toxicity", "trike", "baudelaire", "sheers", "annmarie",
             "poultices", "therapeutics", "inputs", "bailed", "minutest", "pynchon", "jinx", "jackets", "subsections",
             "harmonizes", "caesareans", "freshened", "haring", "disruption", "buckle", "per", "pined", "solemnity",
             "recombined", "chamber", "tangling", "pitiful", "authoritarians", "oort", "ingratiate", "refreshed",
             "bavarian", "generically", "rescheduled", "typewritten", "level", "magnetism", "socialists", "oligocene",
             "resentful", "lambast", "counteroffer", "firefight", "phil", "attenuates", "teary", "demarcated",
             "moralities",
             "electrified", "pettiness", "unpacking", "hungary", "heavies", "tenancies", "tirade", "solaria",
             "scarcity",
             "prettiest", "carrillo", "yodel", "cantilever", "ridiculously", "tagalog", "schismatics", "ossification",
             "hezbollah", "downscaling", "calking", "tapped", "girl", "alba", "lavishness", "stepparents", "integrator",
             "overact", "father", "fobbing", "pb", "require", "toes", "sweats", "prisoners", "mbabane", "hatch",
             "motleyer",
             "worlds", "decentralize", "ingrained", "shekels", "directorship", "negotiating", "hiawatha", "busying",
             "reciprocate", "spinsterhood", "supervened", "scrimmage", "decolonized", "buildups", "sedative", "swats",
             "despotic", "driblets", "redoubting", "stoic", "xeroxes", "satellited", "exteriors", "deregulates",
             "lawful",
             "flunk", "broached", "energetics", "moodily", "popinjays", "shoshone", "misleads", "abduct", "nonevent",
             "flees", "harry", "cleverness", "manipulative", "shoplifts", "tom", "junk", "poniard", "transmute",
             "stricter",
             "trochees", "snack", "relations", "edger", "culminate", "implication", "carjacked", "kissers", "federate",
             "offsetting", "sutures", "wakened", "axis", "boxcars", "grinds", "scenting", "cordoba", "lumberyards",
             "incendiary", "antiphonal", "decipherable", "gilliam", "redecorates", "plum", "nitpickers", "linefeed",
             "awakes", "embittering", "spewing", "annul", "filial", "scarlet", "connors", "sanctum", "scotsman",
             "isobar",
             "activity", "overthrowing", "unseasoned", "tarantulae", "outtake", "diego", "mars", "stunted", "hunted",
             "sublimation", "barbadian", "barbarisms", "epidemic", "assesses", "imposture", "freaks", "detroit",
             "bloodiest", "avails", "prenatal", "connecticut", "guardsmen", "betwixt", "windsock", "neutralized",
             "psychoanalysis", "rubberized", "overproduces", "narcissism", "tallow", "cringes", "resinous",
             "paintbrushes",
             "duality", "paints", "deactivated", "expertly", "speedsters", "coward", "bass", "psychiatrist", "curies",
             "betrays", "bubble", "mellow", "showy", "retarding", "radishes", "coy", "unreservedly", "larks",
             "apportioned",
             "flaccid", "relabelling", "alphabeted", "anointment", "helms", "gillian", "trophying", "breakage",
             "underbrush", "directest", "wingtips", "pretence", "preshrink", "remarries", "addle", "brouhaha",
             "mobbing",
             "g", "dings", "gains", "stockade", "ouch", "particulates", "listens", "habituation", "kill", "crouped",
             "hyperbolae", "hutching", "stoney", "rightness", "davids", "questioned", "ethiopians", "courtliness",
             "delays",
             "navahos", "devils", "keeling", "accelerators", "investigator", "spindling", "illegality", "extremer",
             "revlon", "purity", "bradly", "jut", "machs", "liquidated", "informant", "smartly", "disfigure",
             "parliaments",
             "croup", "teletypes", "impression", "trainee", "implications", "embed", "podiatrists", "jewelled",
             "brokenhearted", "spaceman", "unsteadier", "kitchen", "twirling", "conurbations", "pygmies", "lourdes",
             "watertight", "reassessing", "dempsey", "matriarch", "alas", "abscissae", "decanter", "commentated",
             "sandy",
             "idler", "soybean", "cutoff", "dictate", "credibility", "indeterminable", "release", "blank", "curitiba",
             "pericardia", "probably", "indisposition", "hesitantly", "duff", "ratty", "derivative", "decals",
             "explication", "cockier", "monoxides", "hyperventilate", "genially", "polluter", "divan", "may",
             "convalesces",
             "morpheme", "pupa", "prospered", "tagging", "nerdier", "detached", "spearing", "hilbert", "russeted",
             "amanuensis", "periwinkles", "jujube", "guarantors", "premises", "descanting", "baned", "deviance",
             "sidearms",
             "lamentable", "barristers", "climes", "succulence", "mauve", "oceanographers", "migraine", "bisexual",
             "peruvians", "fatheads", "parsimony", "pilaf", "portly", "conniving", "insidiously", "inventing",
             "constabulary", "cling", "stunting", "accessioned", "deadliness", "overthrow", "expectorant", "agamemnon",
             "blindfold", "striker", "shrugging", "jibes", "appropriateness", "annihilates", "hairs", "proselytes",
             "goads",
             "rankling", "predominated", "hart", "enemies", "culpability", "drank", "martinets", "prospering",
             "dominick",
             "complemented", "invention", "foolscap", "tolerances", "lorelei", "profits", "awarer", "ungodlier",
             "victoriously", "mistrusts", "princes", "drudge", "moderator", "transversed", "disco", "japed", "loomed",
             "incense", "ponds", "gumbel", "disarranges", "coaxes", "technology", "hyde", "debentures", "confidantes",
             "hankered", "savant", "styes", "croupy", "unapproachable", "cisterns", "unto", "duds", "conglomerating",
             "clio", "negroid", "looked", "methodism", "hilario", "balloon", "thesauruses", "integuments",
             "thermometer",
             "slacks", "wigwagging", "gaping", "incensed", "misquotes", "chocking", "patrols", "upcoming", "insists",
             "livings", "thoth", "uselessness", "vibrated", "potluck", "starboard", "uniquer", "boone", "scintillates",
             "darker", "massey", "arbitrariness", "miniaturized", "rousseau", "chiffon", "consortia", "coral",
             "finesses",
             "half", "biked", "unlikeliest", "hilarious", "acrid", "twinkles", "galileo", "outsmarted", "ostentation",
             "cradle", "frats", "misidentifies", "uncleaner", "bacardi", "smoothest", "antwan", "warren", "jingling",
             "stocks", "daumier", "paranoid", "pantaloons", "dishing", "receive", "underpays", "kane", "variation",
             "beset",
             "disobliged", "dreadlocks", "psychics", "twofers", "lieutenants", "pebbling", "interposes", "shingles",
             "profanes", "machining", "dysfunctions", "wolfram", "brut", "nebraskan", "truculently", "copeland",
             "devonian",
             "fuller", "silvia", "philosophers", "cali", "adores", "disquiet", "savvies", "minatory", "blooms",
             "radiotelephones", "paradoxically", "competitions", "gandhi", "weddell", "occludes", "retracing", "kari",
             "dead", "lagoons", "menfolk", "abundant", "enacts", "conferences", "procreation", "steadier", "cols",
             "rabble",
             "unquestioned", "stupefying", "whodunit", "dizzier", "paula", "riposte", "elixirs", "discontented",
             "zimbabweans", "assemblage", "unsalted", "genders", "caldwell", "pulleys", "pureness", "kingston", "vests",
             "hearken", "abuses", "scull", "hussar", "solace", "gondwanaland", "surfacing", "vivienne", "subculture",
             "reciprocal", "expediencies", "projectiles", "segregationist", "prickle", "pooped", "telecommutes", "axes",
             "scenery", "peppery", "parenthesizing", "checked", "trademarked", "unreasonable", "curtly", "dynamically",
             "vulcanize", "airtight", "blotch", "edmund", "stoicism", "scrambles", "whirled", "chasing", "millstones",
             "helplessly", "permalloy", "remanding", "duplicate", "broadsided", "readjustment", "buggers", "quaked",
             "grapples", "democrats", "landfalls", "apprehensively", "turmoiling", "railing", "lothario", "modishly",
             "faggoted", "deflecting", "interment", "dodo", "recreants", "baywatch", "frescoes", "temblor", "brigade",
             "handgun", "bradstreet", "caspar", "godsend", "cochleae", "queered", "unevenness", "hairnet",
             "millimeters",
             "flawless", "plumbing", "disciplinarian", "orbiting", "foothill", "serviettes", "peseta", "windmills",
             "myrdal", "provides", "slowdowns", "clouting", "gainsays", "dishpans", "mediates", "weaker", "shoestrings",
             "gerunds", "potsdam", "chips", "disqualifications", "focus", "quarry", "dwarfs", "laurels", "coverall",
             "reconsidered", "exploded", "distending", "bronzes", "apollonian", "sweeper", "couperin", "gourmets",
             "irreconcilable", "goldbricking", "emotes", "demilitarizes", "lambkin", "grouper", "anyways", "hugs",
             "quizzed", "misstatement", "spectrums", "frigates", "plenipotentiaries", "parasites", "tacitly",
             "savvying",
             "treks", "dissociating", "departing", "resins", "psychiatric", "tablespoonfuls", "aught", "makeup",
             "copping",
             "interwove", "selling", "fantasize", "flamingos", "smolders", "stript", "laverne", "extremely",
             "chattering",
             "imminent", "vaulting", "slackly", "pasteurizes", "goody", "pearls", "conceptualization", "fins",
             "brogues",
             "muskogee", "naziism", "stromboli", "sunflower", "tosca", "luridness", "booing", "zaniness", "creel",
             "bootblacks", "attendants", "swordplay", "impinging", "premiere", "sedimentation", "traffickers", "carrel",
             "observatories", "telltales", "cuckolded", "ampler", "alternately", "shovel", "tasmania", "whooping",
             "methodologies", "pickling", "overseer", "sunnier", "sanchez", "supervening", "viscus", "cramped",
             "santayana",
             "utopias", "intimated", "pianists", "computerizing", "interpolating", "reggie", "horseshoe", "preeminent",
             "qantas", "standish", "flagpoles", "thievery", "admiring", "palefaces", "overflows", "gaea", "monique",
             "sheepskin", "bestiaries", "beethoven", "fleming", "convalescing", "moldier", "snobby", "jewry",
             "hoodwinking",
             "hope", "henri", "listlessly", "doggoning", "anointed", "notable", "talented", "uric", "towards", "flue",
             "arbitrated", "ingredients", "academy", "clutches", "novelle", "parallelling", "confabbed", "synthesized",
             "frontally", "underexpose", "ulcerates", "injuring", "stimulant", "catalytic", "ogle", "throatily", "ions",
             "chores", "spyglasses", "metabolic", "statesmanlike", "tingles", "ossifies", "forge", "coiffing",
             "transepts",
             "autopsy", "colorfast", "winery", "procyon", "sequesters", "amended", "putted", "huff", "fliers",
             "harpooning",
             "protecting", "shipboard", "dwindled", "collations", "stonewalls", "criticism", "thigh", "quarried",
             "knelling", "knitted", "redeemable", "berm", "seventy", "misguides", "schlemiel", "pawn", "ineligibility",
             "lathe", "bosses", "temperance", "haywire", "everglade", "confections", "gruelings", "mindful",
             "paracelsus",
             "quarreled", "furtively", "airdropped", "clodhopper", "transmuting", "whilst", "moldavia", "exploiting",
             "chicories", "unrolling", "shorthand", "antigens", "satirically", "earner", "primmer", "jolly", "perch",
             "nonplussing", "circulars", "hanks", "fingerprinted", "syllogism", "adulate", "nominally", "telecasted",
             "quelled", "accustoming", "backslide", "culminates", "spiraled", "compactor", "gatorade", "cornballs",
             "investor", "cupboards", "deign", "induced", "ewe", "snoopers", "supposed", "glitters", "overlie",
             "ambassadorial", "chancel", "accumulations", "strictest", "thalami", "shops", "moos", "applicators",
             "corncob",
             "dona", "apostrophes", "kibitzes", "rinses", "kemerovo", "confide", "clemenceau", "centenarians",
             "memorialized", "windburn", "nominate", "obscene", "equivocations", "arts", "karloff", "projected",
             "scorned",
             "limping", "lava", "sanitaria", "clementine", "brandies", "unionize", "compacted", "griming", "trilogies",
             "babysit", "congas", "glittery", "pimientos", "phototypesetter", "multivitamin", "carbohydrates", "lode",
             "photographs", "iniquity", "micrometer", "freemasonry", "burros", "marchers", "percentiles", "werewolf",
             "weightlifting", "valedictories", "gacrux", "senselessly", "stoppage", "monolithic", "handy", "overspent",
             "nymphomaniac", "seasick", "misogynistic", "coltrane", "coeval", "inversion", "darkliest", "landfills",
             "barbers", "suppurate", "cavern", "submerge", "illumination", "hesitates", "lashes", "covenants",
             "thomism",
             "aneurism", "disappointed", "gnarls", "sprint", "abash", "frightens", "undoings", "pa", "helicopters",
             "reexamines", "vassal", "blessing", "devaluation", "purports", "urinals", "adjudged", "garaging",
             "pacific",
             "infomercials", "whitewashed", "fawned", "baptisms", "concede", "cornflakes", "fostered", "clewed",
             "tiller",
             "dalmatians", "signification", "boneless", "chunkiness", "omar", "paramedicals", "professor", "unionizing",
             "scripted", "anchors", "tabloid", "alton", "redrafted", "reflexive", "luddite", "lamb", "bidirectional",
             "seaports", "christendom", "gets", "chaperoning", "tchaikovsky", "wasters", "dioxin", "nuke", "apologized",
             "queasily", "fujiwara", "prearranges", "abdul", "upraising", "sparklers", "signposting", "comparison",
             "sb",
             "cherokees", "ungentlemanly", "typing", "waisted", "sputter", "biographers", "waltz", "stanches",
             "upbringings", "smithereens", "tutor", "young", "eloy", "sourdoughs", "clingier", "hoisting", "blazon",
             "homosexuality", "lorries", "kippering", "abacus", "specks", "congressional", "auditing", "lash",
             "eternal",
             "carve", "facade", "defrauds", "neighbored", "musses", "dismount", "lope", "lawbreaker", "deed", "japes",
             "repeal", "factorization", "impetuosity", "sitters", "disorganizing", "fussing", "vale", "epitomized",
             "executrixes", "deprivations", "woodcarvings", "miscalls", "skateboard", "pedicured", "cloakroom",
             "vassaled",
             "innumerable", "knelt", "cellulose", "beams", "uniform", "metatarsals", "meteorologist", "column",
             "burnishes",
             "dentists", "quids", "toasts", "tableland", "archivist", "gladiolas", "replica", "lording", "viewed",
             "polisher", "trooping", "indistinctly", "resisters", "flycatchers", "toughed", "regor", "insolvent",
             "ninnies",
             "truckled", "birthplaces", "telescopic", "abelson", "puritanism", "leanings", "disturbingly",
             "transmission",
             "mortify", "upshot", "newlywed", "adam", "ballplayer", "lockwood", "quirking", "blocs", "theatre",
             "palliatives", "smudges", "marvelled", "ramble", "offside", "indissoluble", "droplets", "fencing",
             "hubbard",
             "estimation", "incorrect", "malarial", "confucian", "games", "sacraments", "trivets", "gammas", "nastiest",
             "merrymakers", "sealskin", "overkilled", "bosser", "strafe", "exclusives", "bouldered", "antiwar",
             "guitarists", "jerry", "earthly", "oscilloscope", "edmonton", "merger", "laminated", "surmountable",
             "casually", "backspaced", "charcoals", "overheating", "caramel", "oldened", "asterisked", "tun", "peafowl",
             "purplest", "skippering", "prep", "congregating", "glaringly", "crummiest", "noreen", "bromide",
             "nomenclatures", "kristin", "purportedly", "vamoosing", "busybody", "crucify", "capote", "milliners",
             "veils",
             "windsurf", "reconnecting", "layering", "ossified", "noble", "tiptoeing", "smiles", "swain", "perihelion",
             "bagels", "obfuscation", "spreadsheets", "buddy", "flints", "planting", "hogwarts", "abusers", "welfare",
             "mouses", "lament", "auras", "unrelieved", "cougars", "cattails", "chubby", "handstands", "woolly",
             "concealment", "mediterraneans", "judas", "electrocardiographs", "skulks", "puttered", "crimean", "liven",
             "odds", "warehousing", "lifeguard", "deepness", "clowns", "blossomed", "constriction", "honest",
             "noisemakers",
             "whist", "overcame", "sulphured", "vertebras", "commiseration", "jolted", "adjourns", "bungles", "sonnies",
             "housekeeper", "buddha", "bolsters", "warlords", "banjarmasin", "militated", "anywheres", "lula",
             "weirdos",
             "raymond", "sections", "taoisms", "pay", "latest", "bights", "carousel", "sups", "lavatory", "conciser",
             "lon",
             "beefburger", "clinically", "snakes", "backslash", "developmental", "squibb", "smote", "mastectomy",
             "genius",
             "sallying", "niagara", "guild", "altai", "ascetics", "marts", "misbehaved", "desired", "pagodas",
             "platypus",
             "freemen", "lovemaking", "transfers", "brewing", "absorbents", "unions", "lite", "wilder", "popovers",
             "yamaha", "faultier", "supplements", "forsythia", "rummy", "propagation", "motorbikes", "velez",
             "unequivocally", "lend", "silliness", "idiosyncratic", "disseminated", "carter", "washed", "dizzying",
             "bedsore", "pawned", "lr", "nubile", "galloped", "subservience", "marlin", "chance", "schooners",
             "faction",
             "clutters", "transmits", "weathercocks", "illustrations", "quell", "senegalese", "touchiest", "psychs",
             "joshes", "shallots", "garrottes", "coifs", "glaswegian", "hydrated", "smirch", "strutting", "arnold",
             "coughing", "tangier", "olympics", "overexposing", "benefactor", "reputably", "snootier", "smuggles",
             "bogus",
             "priories", "chandra", "diplomatics", "muskrat", "forbad", "monasticism", "outshone", "farewell", "thomas",
             "epaulets", "nectarines", "affording", "buckles", "concordance", "lebesgue", "pawed", "lackey", "sweden",
             "confirmatory", "humble", "wizards", "controlling", "scoffing", "worthy", "homely", "lexical", "batteries",
             "chorusing", "inboard", "cotton", "lustrous", "devalued", "herbart", "travestied", "veneered", "maxillas",
             "omelet", "ptarmigans", "alnilam", "submerging", "bucks", "niceties", "yong", "gender", "toileting",
             "biding",
             "caffeine", "lubricant", "dashikis", "balm", "filings", "series", "paraguayan", "fatefully", "craggier",
             "oversexed", "milkweed", "passels", "concretely", "rapiers", "channeled", "multifaceted", "tenth",
             "conflagration", "pivoted", "horribles", "tugs", "fireman", "hull", "semifinalist", "odorous", "carats",
             "uncomfortably", "clappers", "chaffinches", "demagnetize", "limits", "ups", "wimp", "reserved", "busyness",
             "illuminate", "autocratic", "zips", "sculley", "vainest", "conciliators", "vacillations", "daughter",
             "beau",
             "stashes", "mini", "shallow", "divided", "invert", "caesurae", "vibrantly", "germination", "winching",
             "curmudgeon", "hurts", "battens", "lovable", "redistricted", "neighing", "nonexistence", "foghorns",
             "manifesting", "retrofitting", "fictitious", "gracefully", "shetlands", "transistors", "rectitude", "shea",
             "acquisitions", "predetermines", "huts", "blintze", "cortland", "murdered", "leninism", "ninetieths",
             "fractal", "inveighs", "compelled", "ringer", "mistiest", "snorting", "transportation", "dictionaries",
             "khyber", "misspelling", "bifocal", "playmates", "disputant", "neuters", "epidemics", "vijayawada",
             "ambles",
             "splashdowns", "cants", "bandannas", "millennia", "glows", "fowled", "cupped", "laramie", "occupied",
             "gelatine", "scorches", "sidelights", "beagling", "campused", "doer", "gunfighting", "tsitsihar", "marin",
             "fireside", "yellow", "seagram", "strap", "arrivals", "sixty", "lipscomb", "wares", "awfullest",
             "servants",
             "dreamer", "crockery", "mahavira", "brad", "outpourings", "dusty", "shrubs", "briefest", "segments",
             "cartilages", "excommunicated", "generator", "placket", "berate", "emulations", "suspicious", "fortnights",
             "sped", "griding", "panting", "trimaran", "suspend", "retract", "adversity", "regimental", "hammett",
             "wallflower", "tyrannize", "cinemascope", "ambassador", "humerus", "litter", "trying", "sinkable",
             "descents",
             "coveralls", "region", "landslid", "bowed", "zigzagging", "upholstery", "parch", "scratchy", "altitude",
             "angling", "scaldings", "plussed", "babel", "cirrus", "haberdasher", "gayle", "chillest", "catboat",
             "battling", "bellini", "extincts", "appendices", "unmade", "footstool", "deaths", "secretively", "erasmus",
             "agra", "soothsayers", "stillest", "despoils", "affiliated", "mumble", "aleut", "gyp", "purchased", "kory",
             "cesspool", "interacted", "demarcates", "fanciness", "defines", "absorbed", "fireplugs", "pluckiest",
             "misstates", "grenades", "untidiness", "ventricles", "overexpose", "dryad", "tumbler", "chengdu",
             "thistledown", "dork", "unauthorized", "holmes", "downgrading", "syphilises", "trammelled", "sending",
             "afflict", "ornithologist", "serried", "much", "emoluments", "wilfully", "strayed", "canada", "dachshund",
             "compost", "glamorized", "gerrymandering", "senate", "allots", "arsonists", "coloratura", "borderlines",
             "cartooned", "evert", "continents"])
        assert sorted(self.value) == sorted(
            [["evert"], ["cartooned"], ["senate"], ["gerrymandering"], ["glamorized"], ["compost"],
             ["dachshund"], ["wilfully"], ["afflict"], ["trammelled"], ["syphilises"], ["holmes"],
             ["dork"], ["thistledown"], ["chengdu"], ["dryad"], ["ventricles"], ["misstates"],
             ["pluckiest"], ["fireplugs"], ["absorbed"], ["cesspool"], ["purchased"], ["gyp"], ["aleut"],
             ["mumble"], ["affiliated"], ["erasmus"], ["deaths"], ["unmade"], ["bellini"], ["catboat"],
             ["chillest"], ["haberdasher"], ["cirrus"], ["plussed"], ["scaldings"], ["altitude"],
             ["parch"], ["upholstery"], ["zigzagging"], ["bowed"], ["landslid"], ["coveralls"],
             ["ambassador"], ["cinemascope"], ["ornithologist"], ["hammett"], ["regimental"],
             ["adversity"], ["footstool"], ["retract"], ["trimaran"], ["griding"], ["emulations"],
             ["berate"], ["panting"], ["placket"], ["briefest"], ["outpourings"], ["brad"], ["mahavira"],
             ["crockery"], ["dreamer"], ["wares"], ["lipscomb"], ["sixty"], ["arrivals"], ["seagram"],
             ["yellow"], ["marin"], ["gunfighting"], ["sidelights"], ["scorches"], ["occupied"],
             ["fowled"], ["millennia"], ["ambles"], ["neuters"], ["bifocal"], ["snorting"], ["mistiest"],
             ["fractal"], ["leninism"], ["cortland"], ["rectitude"], ["transistors"], ["gracefully"],
             ["nonexistence"], ["redistricted"], ["continents"], ["battens"], ["curmudgeon"], ["shallow"],
             ["mini"], ["conciliators"], ["busyness"], ["wimp"], ["ups"], ["limits"], ["demagnetize"],
             ["chaffinches"], ["carats"], ["odorous"], ["fireman"], ["tugs"], ["horribles"], ["pivoted"],
             ["conflagration"], ["channeled"], ["rapiers"], ["milkweed"], ["oversexed"], ["craggier"],
             ["paraguayan"], ["series"], ["filings"], ["dashikis"], ["lubricant"], ["caffeine"],
             ["ringer"], ["niceties"], ["submerging"], ["ptarmigans"], ["omelet"], ["veneered"],
             ["travestied"], ["herbart"], ["lustrous"], ["cotton"], ["batteries"], ["lexical"], ["homely"],
             ["worthy"], ["controlling"], ["humble"], ["confirmatory"], ["sweden"], ["lackey"], ["pawed"],
             ["lebesgue"], ["concordance"], ["buckles"], ["epaulets"], ["thomas"], ["monasticism"],
             ["chandra"], ["snootier"], ["reputably"], ["overexposing"], ["tangier"], ["smirch"],
             ["chorusing"], ["coifs"], ["garrottes"], ["shallots"], ["joshes"], ["chance"], ["marlin"],
             ["lr"], ["bedsore"], ["dizzying"], ["disseminated"], ["idiosyncratic"], ["lend"],
             ["unequivocally"], ["velez"], ["propagation"], ["rummy"], ["forsythia"], ["supplements"],
             ["faultier"], ["popovers"], ["lite"], ["absorbents"], ["transfers"], ["desired"], ["marts"],
             ["ascetics"], ["sculley"], ["passels"], ["altai"], ["sallying"], ["backslash"],
             ["excommunicated"], ["transportation"], ["snakes"], ["conciser"], ["lavatory"], ["sups"],
             ["bights"], ["pay"], ["taoisms"], ["sections"], ["weirdos"], ["anywheres"], ["banjarmasin"],
             ["buddha"], ["grenades"], ["sonnies"], ["jolted"], ["commiseration"], ["sulphured"],
             ["whist"], ["honest"], ["constriction"], ["blossomed"], ["demarcates"], ["lifeguard"],
             ["smuggles"], ["warehousing"], ["shrubs"], ["liven"], ["puttered"], ["skulks"],
             ["electrocardiographs"], ["judas"], ["mediterraneans"], ["concealment"], ["woolly"],
             ["chubby"], ["cougars"], ["unrelieved"], ["bolsters"], ["auras"], ["alnilam"], ["mouses"],
             ["welfare"], ["strutting"], ["abusers"], ["planting"], ["bagels"], ["perihelion"], ["swain"],
             ["smiles"], ["strayed"], ["noble"], ["ossified"], ["reconnecting"], ["windsurf"], ["veils"],
             ["milliners"], ["vamoosing"], ["purportedly"], ["kristin"], ["bromide"], ["crummiest"],
             ["glaringly"], ["prep"], ["skippering"], ["peafowl"], ["lament"], ["oldened"], ["caramel"],
             ["overheating"], ["backspaced"], ["surmountable"], ["edmonton"], ["deepness"],
             ["oscilloscope"], ["earthly"], ["handstands"], ["jerry"], ["guitarists"], ["quell"],
             ["antiwar"], ["bouldered"], ["exclusives"], ["busybody"], ["bosser"], ["sealskin"],
             ["merrymakers"], ["nastiest"], ["gayle"], ["gammas"], ["tsitsihar"], ["games"],
             ["fortnights"], ["confucian"], ["malarial"], ["estimation"], ["hubbard"], ["droplets"],
             ["offside"], ["marvelled"], ["theatre"], ["quirking"], ["newlywed"], ["upshot"], ["tun"],
             ["transmission"], ["leanings"], ["lon"], ["puritanism"], ["abelson"], ["tenth"],
             ["telescopic"], ["birthplaces"], ["truckled"], ["insolvent"], ["toughed"], ["flycatchers"],
             ["resisters"], ["indistinctly"], ["replica"], ["archivist"], ["toasts"], ["quids"],
             ["dentists"], ["burnishes"], ["meteorologist"], ["nectarines"], ["metatarsals"], ["uniform"],
             ["beams"], ["cellulose"], ["knelt"], ["innumerable"], ["vassaled"], ["pedicured"],
             ["skateboard"], ["executrixes"], ["epitomized"], ["neighing"], ["vale"], ["disorganizing"],
             ["sitters"], ["impetuosity"], ["factorization"], ["repeal"], ["deed"], ["dismount"],
             ["musses"], ["neighbored"], ["serried"], ["carve"], ["eternal"], ["lash"], ["congressional"],
             ["zips"], ["specks"], ["abacus"], ["kippering"], ["lorries"], ["blazon"], ["hoisting"],
             ["incorrect"], ["clingier"], ["sourdoughs"], ["eloy"], ["reserved"], ["young"],
             ["upbringings"], ["stanches"], ["fireside"], ["biographers"], ["sputter"], ["typing"],
             ["cherokees"], ["comparison"], ["signposting"], ["sparklers"], ["upraising"], ["pawned"],
             ["abdul"], ["gender"], ["unions"], ["prearranges"], ["queasily"], ["apologized"], ["dioxin"],
             ["chaperoning"], ["gets"], ["christendom"], ["seaports"], ["bidirectional"], ["balm", "lamb"],
             ["illustrations"], ["redrafted"], ["alton"], ["anchors"], ["lope"], ["scripted"],
             ["unionizing"], ["paramedicals"], ["omar"], ["chunkiness"], ["boneless"], ["signification"],
             ["dalmatians"], ["clewed"], ["fostered"], ["concede"], ["fawned"], ["whitewashed"],
             ["infomercials"], ["pacific"], ["garaging"], ["purports"], ["devaluation"], ["blessing"],
             ["suspicious"], ["fatefully"], ["yong"], ["pa"], ["frightens"], ["abash"], ["gnarls"],
             ["daughter"], ["aneurism"], ["thomism"], ["lashes"], ["lockwood"], ["hesitates"],
             ["submerge"], ["cavern"], ["suppurate"], ["barbers"], ["conniving"], ["alternately"],
             ["peruvians"], ["vulcanize"], ["mauve"], ["watertight"], ["descanting"], ["thoth"],
             ["amanuensis"], ["hilbert"], ["insidiously"], ["bandannas"], ["guarantors"], ["machining"],
             ["nerdier"], ["farewell"], ["tagging"], ["overthrowing"], ["prospered"], ["genially"],
             ["cockier"], ["downscaling"], ["palefaces"], ["maxillas"], ["decals"], ["kitchen"],
             ["obfuscation"], ["mindful"], ["ratty"], ["pettiness"], ["clemenceau"], ["release"],
             ["sunflower"], ["hyperventilate"], ["ossifies"], ["spearing"], ["sandy"], ["reexamines"],
             ["commentated"], ["projectiles"], ["segments"], ["hogwarts"], ["pupa"], ["selling"],
             ["abscissae"], ["indisposition"], ["stupefying"], ["democrats"], ["dwindled"], ["twirling"],
             ["require"], ["babel"], ["embed"], ["implications"], ["delays"], ["trainee"], ["impression"],
             ["utopias"], ["parliaments"], ["outtake"], ["jut"], ["japes"], ["schismatics"], ["servants"],
             ["revlon"], ["fatheads"], ["illegality"], ["investigator"], ["readjustment"], ["millstones"],
             ["questioned"], ["thievery"], ["rulering"], ["pilaf"], ["dusty"], ["grouper"], ["spindling"],
             ["filial"], ["listens"], ["liquidated"], ["particulates"], ["gains"], ["stockade"],
             ["derivative"], ["purity"], ["sadly"], ["ogle"], ["beau"], ["dings"], ["cloakroom"],
             ["cochleae"], ["addle"], ["pretence"], ["inboard"], ["inherits"], ["relabelling"], ["clowns"],
             ["philosophers"], ["flaccid"], ["caesurae"], ["apportioned"], ["khyber"], ["conferences"],
             ["gerunds"], ["radishes"], ["harmonizes"], ["enemies"], ["avails"], ["retarding"], ["booing"],
             ["curies"], ["mbabane"], ["bubble"], ["miniaturized"], ["expertly"], ["unforeseen"],
             ["paracelsus"], ["paints"], ["duff"], ["interpolating"], ["duality"], ["fictitious"],
             ["ambassadorial"], ["twinkles"], ["broadsided"], ["dictionaries"], ["sprint"], ["scotsman"],
             ["interment"], ["neutralized"], ["conductor"], ["decentralize"], ["sanitaria"], ["prenatal"],
             ["bloodiest"], ["multifaceted"], ["aping"], ["barbadian"], ["overact"], ["sublimation"],
             ["discontented"], ["orbiting"], ["cupped"], ["hunted"], ["scintillates"], ["mars"], ["diego"],
             ["reassessing"], ["habituation"], ["sweeper"], ["teletypes"], ["lula"], ["paraphrase"],
             ["muskrat"], ["unseasoned"], ["hilarious"], ["activity"], ["extincts"], ["sanctum"],
             ["scarlet"], ["sidearms"], ["monoxides"], ["jujube"], ["manifolding"], ["annul"], ["smartly"],
             ["ashikaga"], ["embittering"], ["betwixt"], ["nitpickers"], ["tinseled"], ["engrossing"],
             ["epidemics"], ["brokenhearted"], ["sacraments"], ["plum"], ["redecorates"], ["decipherable"],
             ["bucks"], ["naziism"], ["daumier"], ["glaswegian"], ["unrolling"], ["scenting"],
             ["landfills"], ["g"], ["defines"], ["handy"], ["wakened"], ["flippancy"], ["weathercocks"],
             ["temperance"], ["transmits"], ["latest"], ["implication"], ["tarantulae"], ["moos"],
             ["relations"], ["stunting"], ["stricter"], ["transmute"], ["poniard"], ["borderlines"],
             ["laramie"], ["dispossession"], ["urinals"], ["imprison"], ["junk"], ["manipulative"],
             ["cleverness"], ["assemblage"], ["pagodas"], ["harry"], ["observatories"], ["flees"],
             ["crew"], ["competitions"], ["larks"], ["misleads"], ["navahos"], ["apostrophes"],
             ["warlords"], ["documentaries"], ["shoshone"], ["modishly"], ["popinjays"], ["cling"],
             ["broached"], ["redoubting"], ["lawful"], ["cognac"], ["morpheme"], ["unauthorized"],
             ["deregulates"], ["defaulters"], ["xeroxes"], ["probably"], ["coward"], ["driblets"],
             ["sedative"], ["buildups"], ["appendices"], ["decolonized"], ["peacefuller"], ["negroid"],
             ["hilario"], ["awakes"], ["ulcerates"], ["scrimmage"], ["rambles"], ["helms"], ["bradly"],
             ["spinsterhood"], ["column"], ["elicit"], ["lechers"], ["swordplay"], ["hiawatha"],
             ["stashes"], ["sequesters"], ["negotiating"], ["tableland"], ["hussar"], ["directorship"],
             ["attenuates"], ["pantaloons"], ["snack"], ["stoicism"], ["mediates"], ["wilder"], ["worlds"],
             ["dwarfs"], ["lambkin"], ["monique"], ["toes"], ["ramble"], ["stoppage"], ["permalloy"],
             ["demilitarizes"], ["ethiopians"], ["showy"], ["battling"], ["strictest"], ["floodlit"],
             ["kill"], ["winching"], ["participants"], ["genders"], ["prettiest"], ["breakage"],
             ["doggones"], ["reciprocate"], ["positively"], ["crouped"], ["representing"], ["affording"],
             ["zimbabweans"], ["tiller"], ["thermometer"], ["sweats"], ["suspend"], ["matriarch"],
             ["cultivates"], ["humerus"], ["vacillations"], ["pitiful"], ["gladiolas"], ["resinous"],
             ["subliming"], ["vivienne"], ["pencils"], ["cramped"], ["wastrels"], ["ballplayer"],
             ["seasick"], ["phil"], ["hope"], ["freaks"], ["uniquer"], ["vassal"], ["porterhouse"],
             ["vests"], ["flunk"], ["sutures"], ["rabble"], ["grudging"], ["deflecting"], ["lourdes"],
             ["safflower"], ["bussed"], ["keeling"], ["abracadabra"], ["prissy"], ["buns"], ["bisexual"],
             ["gaea"], ["kissers"], ["brew"], ["incendiary"], ["parsley"], ["clutters"], ["deprivations"],
             ["roast"], ["splashdowns"], ["bedevilling"], ["arnold"], ["loathes"], ["psychs"], ["bailed"],
             ["brouhaha"], ["curitiba"], ["blank"], ["boon"], ["gillian"], ["instalment"], ["stunted"],
             ["foghorns"], ["asterisked"], ["overspent"], ["buffalo"], ["lawbreaker"], ["chided"],
             ["talented"], ["nonplussing"], ["hurts"], ["buddy"], ["anglo"], ["nozzle"], ["hairnet"],
             ["savvying"], ["forbad"], ["hesitantly"], ["helicopters"], ["recopy"], ["methodologies"],
             ["bluebell"], ["tom"], ["oligocene"], ["memorialized"], ["dead"], ["offsetting"], ["freemen"],
             ["tagalog"], ["rubberized"], ["shoplifts"], ["fobbing"], ["handgun"], ["neonate"],
             ["gristly"], ["huff"], ["quaked"], ["misbehaved"], ["arts"], ["oort"], ["genius"],
             ["foothill"], ["unpacking"], ["noreen"], ["shovel"], ["blockhead"], ["essequibo"],
             ["oceanographers"], ["mantegna"], ["awarer"], ["enigmas"], ["half"], ["accelerators"],
             ["weddell"], ["confabbed"], ["gewgaw"], ["saki"], ["arbitrariness"], ["treks"],
             ["monochrome"], ["wasters"], ["fuller"], ["connecticut"], ["dwellers"], ["despoils"],
             ["scarcity"], ["smithereens"], ["jewelled"], ["unfriendliest"], ["flints"], ["recommenced"],
             ["pithily"], ["punjabi"], ["synthesized"], ["mossiest"], ["tenancies"], ["parsimony"],
             ["circulars"], ["devalued"], ["solemnity"], ["barristers"], ["carsick"], ["charcoals"],
             ["overproduces"], ["geller"], ["crimean"], ["wiser"], ["raymond"], ["gruelings"], ["tallow"],
             ["bungles"], ["laminated"], ["hyperbolae"], ["charm"], ["ossification"], ["canada"],
             ["carter"], ["mewling"], ["airdropped"], ["walkways"], ["swats"], ["shielded"], ["climes"],
             ["persecuted"], ["squibb"], ["caesareans"], ["lieutenants"], ["strafe"], ["wattage"],
             ["photographs"], ["indeterminable"], ["toxicity"], ["towards"], ["attendants"],
             ["jewishness"], ["involuntary"], ["conurbations"], ["gumbel"], ["carrillo"], ["overseer"],
             ["asphalts"], ["devils"], ["numismatists"], ["putted"], ["locutions"], ["psychiatrist"],
             ["tolerances"], ["styes"], ["jiving"], ["hakka"], ["barbarisms"], ["shortcuts"],
             ["unsteadier"], ["massey"], ["lavishness"], ["darkliest"], ["stoney"], ["duisburg"], ["hull"],
             ["unto"], ["disobliged"], ["foxtrot"], ["odds"], ["impinging"], ["crux"], ["typewritten"],
             ["nonevent"], ["vinson"], ["riposte"], ["soothsayers"], ["grinds"], ["goads"],
             ["subservience"], ["russeted"], ["physical"], ["pioneers"], ["interacted"], ["cattails"],
             ["edmund"], ["clappers"], ["buckle"], ["confidential"], ["neglects"], ["forewomen"],
             ["subsections"], ["insists"], ["trochees"], ["pickling"], ["sarah"], ["yodel"], ["sinkable"],
             ["waltz"], ["marlborough"], ["cartilages"], ["oscilloscopes"], ["may"], ["casually"],
             ["trooping"], ["paralegal"], ["connors"], ["overkilled"], ["foxhound"], ["induced"],
             ["unequalled"], ["collations"], ["cols"], ["smudges"], ["flutists"], ["telephoning"],
             ["soybean"], ["doer", "redo"], ["secretively"], ["teammates"], ["ninetieths"], ["biked"],
             ["acquisitions"], ["provides"], ["outmanoeuvres"], ["expeditiously"], ["airbrush"],
             ["cuckolded"], ["magnetism"], ["linefeed"], ["anointment"], ["imposture"], ["quarry"],
             ["undertakings"], ["coy"], ["aware"], ["playmates"], ["heartening"], ["exteriors"],
             ["migraine"], ["cordoba"], ["adam"], ["periwinkles"], ["silliness"], ["hoodwinking"],
             ["socialists"], ["lucks"], ["micrometer"], ["congaing"], ["firefight"], ["rothko"], ["machs"],
             ["starboard"], ["credibility"], ["outfield"], ["curtly"], ["omelettes"], ["guardsmen"],
             ["retracing"], ["optimist"], ["spaceman"], ["polluter"], ["whodunit"], ["sultans"], ["e"],
             ["brandies"], ["anointed"], ["underbrush"], ["carolingian"], ["haring"], ["paintbrushes"],
             ["lovable"], ["poultices"], ["pynchon"], ["checked"], ["pygmies"], ["katmandu"],
             ["stepparents"], ["huts"], ["fulminations"], ["germination"], ["senegalese"], ["slaver"],
             ["counteroffer"], ["federate"], ["snooping"], ["psychoanalysis"], ["thesauruses"],
             ["couriered"], ["tapir"], ["dunce"], ["dusky"], ["touchiest"], ["distending"], ["vocalizing"],
             ["shingles"], ["overflows"], ["hungary"], ["inventing"], ["forge"], ["monolithic"],
             ["fliers"], ["northerner"], ["ineptly"], ["disappointed"], ["satellited"], ["alas"],
             ["enquiries"], ["explication"], ["docudrama"], ["sultan"], ["sinkers"], ["mortify"],
             ["energetics"], ["occludes"], ["pentathlon"], ["convalesces"], ["tacitly"], ["sip"],
             ["crucify"], ["showered"], ["designates"], ["gelatine"], ["concretely"], ["yamaha"],
             ["electrified"], ["beagling"], ["zippy"], ["tillman"], ["conceptualization"], ["tangling"],
             ["partaking"], ["extremer"], ["extremely"], ["leanne"], ["tabloid"], ["pearls"], ["defrauds"],
             ["carjacked"], ["alba"], ["underwriting"], ["disturbingly"], ["ingredients"], ["cutoff"],
             ["homosexuality"], ["statesmanlike"], ["hatch"], ["phototypesetter"], ["guardrooms"],
             ["portly"], ["tows"], ["propounded"], ["disruption"], ["misidentifies"], ["trike"],
             ["directest"], ["pined"], ["olympias"], ["unreasonable"], ["generically"], ["bogus"],
             ["purplest"], ["annmarie"], ["therapeutics"], ["centenarians"], ["oregonians"], ["inputs"],
             ["polisher"], ["jolly"], ["adjourns"], ["decanter"], ["overexpose"], ["semifinalist"],
             ["heavies"], ["telltales"], ["ingrained"], ["toileting"], ["abduct"], ["diplomatics"],
             ["hugs"], ["flamingos"], ["deactivated"], ["jinx"], ["gilliam"], ["busying"], ["traffickers"],
             ["uncomfortably"], ["adulterate"], ["lovemaking"], ["miscalls"], ["jackets"], ["per"],
             ["nymphomaniac"], ["assesses"], ["snell"], ["succulence"], ["congregating"], ["edger"],
             ["despotic"], ["glows"], ["hezbollah"], ["percentiles"], ["authoritarians"], ["vaulting"],
             ["calking"], ["vibrantly"], ["bavarian"], ["penknives"], ["flue"], ["ridiculously"],
             ["metabolic"], ["variation"], ["trophying"], ["blintze"], ["bestiaries"], ["downgrading"],
             ["freemasonry"], ["premises"], ["croup"], ["chocking"], ["auditing"], ["undoings"],
             ["resins", "rinses"], ["upcoming"], ["alphabeted"], ["cringes"], ["paula"], ["nominally"],
             ["professor"], ["accumulations"], ["resentful"], ["segregationist"], ["karloff"],
             ["refreshed"], ["lambast"], ["betrays"], ["moralities"], ["shorthorns"], ["wingtips"],
             ["cantilever"], ["beefburger"], ["noisemakers"], ["ewe"], ["speedsters"], ["shetlands"],
             ["facade"], ["peppery"], ["lording"], ["helplessly"], ["boxcars"], ["tapped"], ["integrator"],
             ["solaria"], ["manifesting"], ["deadliness"], ["knelling"], ["bitched"], ["ingratiate"],
             ["consortia"], ["illumination"], ["queered"], ["lode"], ["expectorant"], ["striker"],
             ["shrugging"], ["compelled"], ["shea"], ["guild"], ["jibes"], ["coloratura"],
             ["appropriateness"], ["engining"], ["compacted"], ["parenthesizing"], ["hairs"], ["pulleys"],
             ["proselytes"], ["predominated"], ["agra"], ["abuses"], ["quarreled"], ["hart"], ["sending"],
             ["culpability"], ["underexpose"], ["ineligibility"], ["prospering"], ["dominick"], ["trying"],
             ["complemented"], ["tumbler"], ["isobar"], ["invention"], ["foolscap"], ["layering"],
             ["luddite"], ["rousseau"], ["lorelei"], ["profits"], ["epidemic"], ["agamemnon"],
             ["serviettes"], ["ungodlier"], ["victoriously"], ["regor"], ["parallelling"], ["chamber"],
             ["princes"], ["disqualifications"], ["drudge"], ["misspelling"], ["muskogee"], ["moderator"],
             ["transversed"], ["cornflakes"], ["disco"], ["spewing"], ["congas"], ["pb"], ["japed"],
             ["generator"], ["mellow"], ["incense"], ["outshone"], ["ponds"], ["coaxes"], ["invert"],
             ["technology"], ["menfolk"], ["hyde"], ["angling"], ["livings"], ["stocks"], ["unreservedly"],
             ["debentures"], ["steadier"], ["confidantes"], ["hankered"], ["savant"], ["telecommutes"],
             ["applicators"], ["primmer"], ["covenants"], ["sterling"], ["croupy"], ["unapproachable"],
             ["fanciness"], ["chiffon"], ["conglomerating"], ["cisterns"], ["duds"], ["clio"],
             ["carousel"], ["axes"], ["courtliness"], ["looked"], ["reconsidered"], ["strap"], ["balloon"],
             ["anyways"], ["reggie"], ["knitted"], ["integuments"], ["culminate"], ["disciplinarian"],
             ["slacks"], ["wigwagging"], ["gaping"], ["patrols"], ["fencing"], ["divan"], ["uselessness"],
             ["apprehensively"], ["potluck"], ["spender"], ["highness"], ["fins"], ["recombined"],
             ["boone"], ["level"], ["dishpans"], ["potsdam"], ["matchbook"], ["darker"], ["spreadsheets"],
             ["coral"], ["procreation"], ["finesses"], ["unlikeliest"], ["acrid"], ["boosts"], ["notable"],
             ["lathe"], ["carbohydrates"], ["outsmarted"], ["developmental"], ["bootblacks"], ["cradle"],
             ["uncleaner"], ["mobbing"], ["bacardi"], ["sb"], ["reflexive"], ["smoothest"], ["antwan"],
             ["warren"], ["stendhal"], ["caldwell"], ["podiatrists"], ["jingling"], ["paranoid"],
             ["transepts"], ["dishing"], ["receive"], ["coughing"], ["imminent"], ["corncob"],
             ["underpays"], ["kane"], ["campused"], ["loomed"], ["caspar"], ["awfullest"], ["father"],
             ["dreadlocks"], ["moodily"], ["goody"], ["psychics"], ["twofers"], ["shekels"], ["pebbling"],
             ["interposes"], ["stillest"], ["girl"], ["coiffing"], ["faction"], ["profanes"], ["baptisms"],
             ["fleming"], ["region"], ["dysfunctions"], ["lavishing"], ["wolfram"], ["brut"],
             ["baudelaire"], ["detonated"], ["paglia"], ["ions"], ["nomenclatures"], ["nebraskan"],
             ["truculently"], ["copeland"], ["brewing"], ["maliced"], ["devonian"], ["cali"], ["bronzes"],
             ["hutching"], ["adores"], ["savvies"], ["wizards"], ["disquiet"], ["much"], ["narcissism"],
             ["blooms"], ["motorbikes"], ["aught"], ["airtight"], ["radiotelephones"], ["janitorial"],
             ["paradoxically"], ["gandhi"], ["untidiness"], ["chucking"], ["mythologists"], ["chasing"],
             ["kari"], ["silvia"], ["lagoons"], ["abundant"], ["illuminate"], ["enacts"], ["sped"],
             ["protecting"], ["unquestioned"], ["remanding"], ["incensed"], ["pericardia"], ["perch"],
             ["dizzier"], ["vibrated"], ["copping"], ["elixirs"], ["unsalted"], ["pureness"], ["nuke"],
             ["kingston"], ["hearken"], ["kory"], ["scull"], ["schooners"], ["viewed"], ["confide"],
             ["davids"], ["solace"], ["gondwanaland"], ["olympics"], ["surfacing"], ["biding"],
             ["vertebras"], ["floodgate"], ["subculture"], ["reciprocal"], ["expediencies"], ["pooped"],
             ["dippers"], ["scenery"], ["waisted"], ["trademarked"], ["smote"], ["lumberyards"],
             ["dynamically"], ["scrambles"], ["whirled"], ["mistrusts"], ["kibitzes"], ["duplicate"],
             ["belittle"], ["buggers"], ["baned"], ["grapples"], ["beset"], ["landfalls"], ["railing"],
             ["dempsey"], ["lothario"], ["faggoted"], ["methodism"], ["clouting"], ["waterlogged"],
             ["frescoes"], ["burros"], ["rankling"], ["temblor"], ["parasites"], ["smolders"], ["brigade"],
             ["bradstreet"], ["reprint"], ["minutest"], ["unevenness"], ["millimeters"], ["flawless"],
             ["peseta"], ["windmills"], ["myrdal"], ["slowdowns"], ["brogues"], ["supervened"], ["tirade"],
             ["spectrums"], ["shoestrings"], ["focus"], ["iniquity"], ["laurels"], ["hurl"],
             ["chattering"], ["coverall"], ["palliatives"], ["exploded"], ["lamentable"], ["bass"],
             ["apollonian"], ["couperin"], ["murdered"], ["gourmets"], ["trivets"], ["irreconcilable"],
             ["idler"], ["frats"], ["plenipotentiaries"], ["goldbricking"], ["predetermines"], ["emotes"],
             ["scratchy"], ["antiphonal"], ["nominate"], ["demarcated"], ["quizzed"], ["misstatement"],
             ["snoopers"], ["frigates"], ["dissociating"], ["departing"], ["shrew"], ["psychiatric"],
             ["tablespoonfuls"], ["turmoiling"], ["makeup"], ["descents"], ["deviance"], ["interwove"],
             ["fantasize"], ["stript"], ["laverne"], ["niagara"], ["preshrink"], ["pasteurizes"],
             ["detached"], ["stromboli"], ["tosca"], ["satirically"], ["retrofitting"], ["gainsays"],
             ["werewolf"], ["galloped"], ["semimonthlies"], ["dictate"], ["luridness"], ["zaniness"],
             ["overthrow"], ["valedictories"], ["vainest"], ["galileo"], ["weaker"], ["creel"],
             ["indissoluble"], ["ostentation"], ["exploiting"], ["hydrated"], ["tiptoeing"],
             ["woodcarvings"], ["tutor"], ["drank"], ["premiere"], ["platypus"], ["sedimentation"],
             ["teary"], ["carrel"], ["ampler"], ["tasmania"], ["detroit"], ["whooping"], ["sunnier"],
             ["marchers"], ["blocs"], ["understate"], ["recreants"], ["sanchez"], ["priories"],
             ["supervening"], ["viscus"], ["straightedges"], ["santayana"], ["annihilates"], ["intimated"],
             ["computerizing"], ["horseshoe"], ["deprecating"], ["martinets"], ["gatorade"],
             ["preeminent"], ["qantas"], ["standish"], ["motleyer"], ["flagpoles"], ["admiring"],
             ["godsend"], ["sheepskin"], ["arsonists"], ["beethoven"], ["convalescing"], ["prisoners"],
             ["moldier"], ["snobby"], ["henri"], ["nubile"], ["colorfast"], ["baywatch"], ["listlessly"],
             ["scoffing"], ["jewry"], ["doggoning"], ["slackly"], ["uric"], ["academy"], ["clutches"],
             ["novelle"], ["dona"], ["frontally"], ["estimate"], ["injuring"], ["vijayawada"],
             ["clinically"], ["windburn"], ["stimulant"], ["disputant"], ["sheers"], ["plumbing"],
             ["catalytic"], ["throatily"], ["chores"], ["spyglasses"], ["tingles"], ["misdiagnoses"],
             ["blotch"], ["autopsy"], ["wallflower"], ["moldavia"], ["winery"], ["rightness"], ["procyon"],
             ["amended"], ["ouch"], ["harpooning"], ["shipboard"], ["stonewalls"], ["minatory"],
             ["criticism"], ["militated"], ["thigh"], ["capote"], ["tchaikovsky"], ["quarried"],
             ["informant"], ["redeemable"], ["telecasted"], ["berm"], ["divided"], ["seventy"],
             ["disfigure"], ["pianists"], ["misguides"], ["schlemiel"], ["merger"], ["prickle"], ["chips"],
             ["pawn"], ["bosses"], ["misquotes"], ["haywire"], ["overcame"], ["everglade"], ["arbitrated"],
             ["confections"], ["furtively"], ["disarranges"], ["clodhopper"], ["transmuting"], ["whilst"],
             ["ungentlemanly"], ["constabulary"], ["axis"], ["chicories"], ["inveighs"], ["shorthand"],
             ["antigens"], ["ninnies"], ["hanks"], ["quelled"], ["earner"], ["fingerprinted"],
             ["multivitamin"], ["freshened"], ["syllogism"], ["adulate"], ["accustoming"], ["backslide"],
             ["tyrannize"], ["fussing"], ["culminates"], ["blindfold"], ["spiraled"], ["blacktop"],
             ["compactor"], ["cornballs"], ["investor"], ["adjudged"], ["cupboards"], ["allots"],
             ["remarries"], ["deign"], ["supposed"], ["glitters"], ["rescheduled"], ["overlie"],
             ["chancel"], ["accessioned"], ["thalami"], ["autocratic"], ["shops"], ["kemerovo"],
             ["litter"], ["obscene"], ["washed"], ["mastectomy"], ["equivocations"], ["projected"],
             ["scorned"], ["stylize"], ["limping"], ["benefactor"], ["housekeeper"], ["dodo"], ["lava"],
             ["clementine"], ["unionize"], ["emoluments"], ["fends"], ["stoic"], ["griming"], ["windsock"],
             ["trilogies"], ["babysit"], ["glittery"], ["pimientos"], ["weightlifting"], ["cants"],
             ["gacrux"], ["senselessly"], ["misogynistic"], ["coltrane"], ["coeval"], ["fujiwara"],
             ["inversion"]])
